server:
  port: 3000
spring:
  messages:
    basename: i18n/messages
    encoding: UTF-8
    cache-duration: 3
    always-use-message-format: true
    fallback-to-system-locale: true
    use-code-as-default-message: true
  application:
    name: memo-api
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres?currentSchema=public
    username: postgres
    password: Qwer!234
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        jdbc.time_zone: UTC
        connection.isolation: READ_COMMITED
        enable_lazy_load_no_trans: true
        format_sql: true
        generate_statistics: true
        dialect: org.hibernate.dialect.PostgreSQL94Dialect
        globally_quoted_identifiers: true
    open-in-view: false
    show-sql: true