server:
  port: 3000
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
  profiles:
    active: local
  application:
    name: memo-api
  messages:
    basename: i18n/messages
    encoding: UTF-8
    cache-duration: 3
    always-use-message-format: true
    fallback-to-system-locale: true
    use-code-as-default-message: true
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        jdbc.time_zone: UTC
        connection.isolation: READ_COMMITED
        enable_lazy_load_no_trans: true
        format_sql: true
        generate_statistics: true
        globally_quoted_identifiers: true
    open-in-view: false
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect